HEADER:
  label: "About me"

PRESENTATION:
  description: |
    I'm Dinis. I am a Data Scientist with over 5 years of experience, specializing in BI analytics, data analysis, and machine learning. My expertise spans various industries, including healthcare, where I led telemedicine initiatives and developed machine learning models to detect skin cancer.
    
    In addition to data science, I have a solid foundation in medicine, which adds unique value to my work in analyzing and improving healthcare data.
DOING:
  enabled: true
  label: "What I'm doing"
  items:
    - title: "DA & ML"
      icon: "config/assets/icons/mobile.svg"
      description: "Professional development of applications for iOS and Android."
    - title: "DevOps"
      icon: "config/assets/icons/laptop-code.svg"
      description: "High-quality development of sites at the professional level."

SKILLS:
  enabled: true
  label: "Soft Skills"
  items:
    - title: "Fast Learner"
      icon: "config/assets/icons/bolt.svg"
      description: "I have the ability to quickly acquire new knowledge and adapt to changing technological environments."
    - title: "Teamwork"
      icon: "config/assets/icons/user.svg"
      description: "I collaborate effectively in multidisciplinary projects and communicate clearly with team members."
    - title: "Problem Solving"
      icon: "config/assets/icons/gear.svg"
      description: "I am creative and efficient in identifying and solving technical problems."

TECHNOLOGIES:
  enabled: true
  label: "Tech Experience"
  items:
    - title: "Python"
      icon: "config/assets/icons/python.svg"
    - title: "Git"
      icon: "config/assets/icons/git.svg"
    - title: "Pandas"
      icon: "config/assets/icons/pandas.svg"
    - title: "AI"
      icon: "config/assets/icons/ai.svg"
    - title: "Linux"
      icon: "config/assets/icons/linux.svg"
