# We are using the ionicons icon set https://ionic.io/ionicons
# For example, to add a linkedin icon:
# <ion-icon name="logo-linkedin"></ion-icon>
# - icon: "logo-linkedin"

HEADER:
  label: "Show Contacts"

USER:
  role: "Data Scientist"
  name: "Dinis Akulov"
  username: "dinis-a" 
  avatar: "config/assets/avatars/my-avatar.png"

INFO:
  - label: "Email"
    value: "akulov.dinis@gmail.com"
    icon: "mail-outline"
  - label: "Birthday"
    value: "June 29, 1990"
    icon: "calendar-outline"
  - label: "Location"
    value: "Kazan, Tatarstan, Russia"
    icon: "location-outline"

SOCIAL:
  - icon: "logo-linkedin"
    url: "https://www.linkedin.com/in/dinis-akulov"
  - icon: "logo-github"
    url: "https://github.com/dinis-a"
  - icon: "paper-plane-outline"
    url: "https://t.me/dinis_n"
