HEADER:
  label: "Portfolio"

PROJECTS:
  - title: "Flutter Cinemapedia App"
    category: "Mobile development"
    image: "https://i.imgur.com/ANDVQ4o.png"
    url: "https://github.com/ivansaul/flutter_cinemapedia_app#screenshots"
