HEADER:
  label: "Resume"

EDUCATION:
  enabled: true
  label: "Education"
  items:
    - period: "2007 â€” 2013"
      institution: "Pavlov Saint Petersburg State Medical University"
      description: "General Medicine"
    - period: "2013 â€” 2015"
      institution: "North-Western State Medical University named after I.I. Mechnikov"
      description: "Neurosurgery"
    - period: "2024 â€” 2027"
      institution: "Russian New University"
      description: "Masterâ€™s degree in Computer Science with a specialization in Artificial Intelligence Systems"

EXPERIENCE:
  enabled: true
  label: "Experience"
  items:
    - period: "2015 â€” 2018"
      position: "Freelance â€” Scientific Writer"
      description: "Authored 193 scientific articles in the fields of medicine, biology, and psychology."
    - period: "2011 â€” 2019"
      position: "Medical Worker"
      description: |
        Worked as a doctor, emergency medical technician (EMT), and nurse. Acquired extensive experience in the field of medicine:
          <br>
          * 09/2018 â€“ 11/2019: General Practitioner (Telemedicine). World Telehealth Company LLC, Hanover, Maryland, United States<br>
          * 06/2013 â€“ 08/2015: General Practitioner. City Medical and Social Center, St. Petersburg, Russia<br>
          * 11/2010 â€“ 03/2013: Nurse. Cardiovascular Surgery Department (10/2011 â€“ 03/2013), Ophthalmology Department (11/2010 â€“ 10/2011). St. Petersburg State Pavlov Medical University, St. Petersburg, Russia<br>
          * 06/2011 â€“ 08/2011: Paramedic. Ivanovo City Hospital, Ivanovo, Russia<br>
    - period: "2018 â€” 2020"
      position: "World Telehealth Company LLC â€” CEO"
      description: "Founded and developed a telemedicine company from scratch. Developed an ML model for detecting skin tumor diseases. Increased the number of employees to 9. Conducted over 300 telemedicine consultations for citizens of Chile and Mexico."
    - period: "2023 â€” 2024"
      position: "ProgKids â€” Senior Data Analyst"
      description: "Built a data analytics system from scratch. Developed a call monitoring system for sales managers using large language modelsÑŽ. Designed and implemented a comprehensive monitoring and alert system that reduced issue resolution time by 31% and minimized operational disruptions by 21%."
    - period: "2024 â€” Present"
      position: "VK â€” Lead Data Scientist"
      description: ""

LANGUAGES:
  enabled: true
  display_progress_bars: true
  display_percentage_values: true
  label: "Languages"
  items:
    - language: "ðŸ‡¸ðŸ‡¦ Arabic - Elementary / Communicative - A2"
      proficiency: "30%"
    - language: "ðŸ‡ºðŸ‡¸ English - Advanced"
      proficiency: "75%"
    - language: "ðŸ‡ªðŸ‡¸ Spanish - Proficient - (Diploma of Spanish as a Foreign Language, Level C1)"
      proficiency: "90%"
    - language: "ðŸ‡·ðŸ‡º Russian - Native speaker"
      proficiency: "100%"

SKILLS:
  enabled: true
  display_progress_bars: true
  display_percentage_values: true
  label: "My Skills"
  items:
    - skill: "Python"
      proficiency: "100%"
    - skill: "C++ (pybind11)"
      proficiency: "20%"
    - skill: "PySpark"
      proficiency: "90%"
    - skill: "Bash"
      proficiency: "70%"
    - skill: "Docker"
      proficiency: "80%"
    - skill: "PostgreSQL"
      proficiency: "80%"
    - skill: "Git"
      proficiency: "80%"
    - skill: "Statistical analysis"
      proficiency: "80%"
    - skill: "PyTorch"
      proficiency: "80%"

