HEADER:
  label: "Resume"

EDUCATION:
  enabled: true
  label: "Education"
  items:
    - period: "2007 ‚Äî 2013"
      institution: "Pavlov Saint Petersburg State Medical University"
      description: "Specialist Degree in General Medicine"
    - period: "2013 ‚Äî 2015"
      institution: "North-Western State Medical University named after I.I. Mechnikov"
      description: "Residency in Neurosurgery"
    - period: "2024 ‚Äî 2027"
      institution: "RosNOU"
      description: "Master‚Äôs degree in Computer Science with a specialization in Artificial Intelligence Systems"

EXPERIENCE:
  enabled: true
  label: "Experience"
  items:
    - period: "2015 ‚Äî 2018"
      position: "Freelance ‚Äî Scientific Writer"
      description: "Authored 193 scientific articles in the fields of medicine, biology, and psychology."
    - period: "2011 ‚Äî 2019"
      position: "Medical Worker"
      description: |
        Worked as a doctor, emergency medical technician (EMT), and nurse. Acquired extensive experience in the field of medicine:
          <br>
          * 09/2018 ‚Äì 11/2019: General Practitioner (Telemedicine). World Telehealth Company LLC, Hanover, Maryland, United States<br>
          * 06/2013 ‚Äì 08/2015: General Practitioner. City Medical and Social Center, St. Petersburg, Russia<br>
          * 11/2010 ‚Äì 03/2013: Nurse. Cardiovascular Surgery Department (10/2011 ‚Äì 03/2013), Ophthalmology Department (11/2010 ‚Äì 10/2011). St. Petersburg State Pavlov Medical University, St. Petersburg, Russia<br>
          * 06/2011 ‚Äì 08/2011: Paramedic. Ivanovo City Hospital, Ivanovo, Russia<br>
    - period: "2018 ‚Äî 2020"
      position: "World Telehealth Company LLC ‚Äî CEO"
      description: "Founded and developed a telemedicine company from scratch. Developed an ML model for detecting skin tumor diseases. Increased the number of employees to 9. Conducted over 300 telemedicine consultations for citizens of Chile and Mexico."
    - period: "2020 ‚Äî 2023"
      position: "Freelance ‚Äî Data Scientist"
      description: "Delivered data analysis, visualization, and predictive modeling solutions for clients.  Turned complex data into actionable insights to support decision-making."
    - period: "2023 ‚Äî 2024"
      position: "ProgKids ‚Äî Senior Data Analyst"
      description: "Built a data analytics system from scratch. Developed a call monitoring system for sales managers using large language models—é. Designed and implemented a comprehensive monitoring and alert system that reduced issue resolution time by 31% and minimized operational disruptions by 21%."
    - period: "2024 ‚Äî Present"
      position: "VC ‚Äî Lead Data Scientist"
      description: ""

COURSES:
  enabled: true
  label: "Courses"
  items:
    - period: "2014"
      institution: "Medtronic"
      description: "Practical Aspects of intraoperative neuromonitoring application in neurosurgery"
    - period: "2018"
      institution: "Black Sea Yacht School"
      description: "VHF Marine Communications Master SRC, International Bareboat Skipper Sail"
    - period: "2020"
      institution: "Ufa University of Science and Technology"
      description: "Machine Learning for Biomedical Data Processing"
    - period: "2020"
      institution: "Academy of Professional Standards"
      description: "Qualification upgrading course (specialty ‚ÄúNeurosurgery‚Äù)"
    - period: "2022"
      institution: "Yandex"
      description: "Data Science Specialist"
    - period: "2022"
      institution: "Tomsk State University"
      description: "Data Analyst"
    - period: "2025"
      institution: "Karpov Courses"
      description: "Data Science Training Simulator"

ADDITIONAL:
  enabled: true
  label: "Additional"
  items:
    - period: "04/2010"
      institution: "Scientific conference"
      description: "III degree diploma in scientific conference ‚ÄúCurrent issues of experimental and clinical medicine ‚Äì 2010‚Äù"
    - period: "2018"
      institution: "Instituto Cervantes"
      description: "Diploma of Spanish as a Foreign Language, Level C1"

LANGUAGES:
  enabled: true
  display_progress_bars: true
  display_percentage_values: true
  label: "Languages"
  items:
    - language: "üá∫üá∏ English - Advanced"
      proficiency: "75%"
    - language: "üá™üá∏ Spanish - Proficient"
      proficiency: "90%"
    - language: "üá∑üá∫ Russian - Native speaker"
      proficiency: "100%"
    - language: "üá∏üá¶ Arabic - Elementary / Communicative - A2"
      proficiency: "30%"

SKILLS:
  enabled: true
  display_progress_bars: true
  display_percentage_values: true
  label: "My Skills"
  items:
    - skill: "Python"
      proficiency: "100%"
    - skill: "SQL"
      proficiency: "90%"
    - skill: "PyTorch"
      proficiency: "80%"
    - skill: "PySpark"
      proficiency: "90%"
    - skill: "Docker, Docker Swarm"
      proficiency: "80%"
    - skill: "Statistical analysis"
      proficiency: "90%"
    - skill: "Airflow, MLFlow"
      proficiency: "70%"
    - skill: "Git"
      proficiency: "80%"
    - skill: "Bash"
      proficiency: "70%"
    - skill: "HDFS, Hive, Hue, Yarn"
      proficiency: "50%"
    - skill: "C++ (pybind11)"
      proficiency: "20%"

